version: '3.8'
services:
  playground:
    container_name: dev_app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/home/fastAPI-Playground
    ports:
      - "7777:8000"
    environment:
      ENVIRONMENT: ${ENVIRONMENT}
      SYNC_SQLALCHEMY_DATABASE_URL: ${SYNC_SQLALCHEMY_DATABASE_URL}
      ASYNC_SQLALCHEMY_DATABASE_URL: ${ASYNC_SQLALCHEMY_DATABASE_URL}
      REDIS_URL: ${REDIS_URL}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PASSWORD: ${REDIS_PASSWORD}

    depends_on:
      - db
    restart: on-failure
    networks:
      - fastapi_network

  db:
    container_name: dev_mysql
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: test  # Set the root password here
      MYSQL_DATABASE: fastapi_playground  # Optional: Define a database to be created
      MYSQL_USER: fastapi_user  # Define a regular user (not root)
      MYSQL_PASSWORD: test  # Set password for the regular user
    ports:
      - "13306:3306"
    networks:
      - fastapi_network

  redis:
    container_name: dev_redis
    image: redis:7.2.5-alpine
    hostname: redis
    command:
      - 'redis-server'
      - '--requirepass myStrongPassword'
    ports:
      - "16379:6379"
    networks:
      - fastapi_network
networks:
  fastapi_network:

volumes:
  mysql_data: