"""add User to Answer

Revision ID: 1a1ff7f9ddb6
Revises: 302740e2cd3b
Create Date: 2024-04-12 20:23:08.102884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1a1ff7f9ddb6'
down_revision: Union[str, None] = '302740e2cd3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer', sa.Column('user_id', sa.Integer(), nullable=True))
    op.alter_column('answer', 'content',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.create_foreign_key(op.f('fk_answer_user_id_users'), 'answer', 'users', ['user_id'], ['id'])
    op.alter_column('question', 'content',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('question', 'content',
               existing_type=sa.String(length=255),
               type_=mysql.TEXT(),
               existing_nullable=False)
    op.drop_constraint(op.f('fk_answer_user_id_users'), 'answer', type_='foreignkey')
    op.alter_column('answer', 'content',
               existing_type=sa.String(length=255),
               type_=mysql.TEXT(),
               existing_nullable=False)
    op.drop_column('answer', 'user_id')
    # ### end Alembic commands ###
