"""add modify_date to Answer and Question

Revision ID: 9328f6a3450f
Revises: 1a1ff7f9ddb6
Create Date: 2024-04-13 00:02:48.061412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9328f6a3450f'
down_revision: Union[str, None] = '1a1ff7f9ddb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer', sa.Column('modify_date', sa.DateTime(), nullable=True))
    op.add_column('question', sa.Column('modify_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question', 'modify_date')
    op.drop_column('answer', 'modify_date')
    # ### end Alembic commands ###
