"""restart

Revision ID: 4e00a6115607
Revises: 
Create Date: 2024-04-18 22:26:11.011433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e00a6115607'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sync_example',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('modify_date', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_sync_example_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sync_example'))
    )
    op.create_index(op.f('ix_sync_example_create_date'), 'sync_example', ['create_date'], unique=False)
    op.create_index(op.f('ix_sync_example_description'), 'sync_example', ['description'], unique=False)
    op.create_index(op.f('ix_sync_example_id'), 'sync_example', ['id'], unique=False)
    op.create_index(op.f('ix_sync_example_modify_date'), 'sync_example', ['modify_date'], unique=False)
    op.create_index(op.f('ix_sync_example_name'), 'sync_example', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sync_example_name'), table_name='sync_example')
    op.drop_index(op.f('ix_sync_example_modify_date'), table_name='sync_example')
    op.drop_index(op.f('ix_sync_example_id'), table_name='sync_example')
    op.drop_index(op.f('ix_sync_example_description'), table_name='sync_example')
    op.drop_index(op.f('ix_sync_example_create_date'), table_name='sync_example')
    op.drop_table('sync_example')
    # ### end Alembic commands ###
